
                
                
  /secret/history/:
    get:
      tags:
        - secret
      summary: 历史发布秘密 
      description: get history of secrets
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: token
          in: header
          required: true
          type: string 
      responses:
        200:
          description: successful operation
          schema:
            type: object
            properties:
              msg:
                type: string
              history:
                type: array
                items:
                  properties:
                    secret_id :
                      type: string  #不显示
                    content:
                      type: string
                    send_time:
                      type: string
                    colour:
                      type: string
        400:
          description: 请求失败 
          schema:
            type: object
            properties:
              msg:
                type: string
        401:
          description: 身份认证错误
          schema:
            type: object
            properties:
              msg:
                type: string
                
  /comment/history/{secret_id}/:
    get:
      tags:
        - comment
      summary: 查看秘密的评论 
      description: get history of comments
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: token
          in: header
          required: true
          type: string 
        - name: secret_id
          in: path
          required: true
          type: string
      responses:
        200:
          description: successful operation
          schema:
            type: object
            properties:
              msg:
                type: string
              history:
                type: array
                items:
                  properties:
                    comment_id :
                      type: string  #不显示
                    content:
                      type: string
                    comment_time:
                      type: string
        400:
          description: 请求错误
          schema:
            type: object
            properties:
              msg:
                type: string
        401:
          description: 身份认证错误
          schema:
            type: object
            properties:
              msg:
                type: string  
  
    
  
                      
  /remind/night/remindbox/view/:
    get:
      tags:
        - remind
      summary: 查看所有黑夜消息提醒 
      parameters:
        - name: token
          in: header
          required: true
          type: string
      responses:
        200:
          description: successful operation
          schema:
            type: object
            properties:
              msg:
                type: string
              commentdata:
                type: array
                items:
                  properties:
                    comment_time:
                      type: string
                    comment:
                      type: string
                    secret_id:
                      type: integer
        401:
          description: 身份认证错误
          schema:
            type: object
            properties:
              msg:
                type: string
            
 
                
  /secret/create/:
    post:
      tags:
        - secret
      summary: 发布秘密
      parameters:
        - name: token
          in: header
          required: true
          type: string
        - name: data
          in: body
          schema:
            required:
              - content
              - sendTime
            properties:
              colour:
                type: string
              content:
                type: string
              sendTime:
                type: string
      responses:
        200:
          description: success
          schema:
            type: object
            properties:
              msg:
                type: string
              secretId:
                type: integer
        400:
          description: 发布失败 
          schema:
            type: object
            properties:
              msg:
                type: string
        401:
          description: 身份认证错误
          schema:
            type: object
            properties:
              msg:
                type: string


  /comment/create/:
    post:
      tags:
        - comment
      summary: 发布评论 
      parameters:
        - name: token
          in: header
          required: true
          type: string
        - name: data
          in: body
          schema:
            required:
              - comment_time
              - content
              - secret_id
            properties:
              comment_time:
                type: integer
              comment:
                type: string
              secret_id:
                type: integer
      responses:
        200:
          description: success
          schema:
            type: object
            properties:
              msg:
                type: string
        400:
          description: 请求错误
          schema:
            type: object
            properties:
              msg:
                type: string
        401:
          description: 身份认证错误
          schema:
            type: object
            properties:
              msg:
                type: string
                
  
  /secret/delete/{secret_id}/:
    delete:
      tags:
        - secret
      summary: 删除秘密
      parameters:
        - name: token
          in: header
          required: true
          type: string
        - name: secretId
          in: query
          required: true
          type: string      
      responses:
        200:
          description: success
          schema:
            type: object
            properties:
              msg:
                type: string

        400:
          description: 请求错误
          schema:
            type: object
            properties:
              msg:
                type: string
        401:
          description: 身份认证错误
          schema:
            type: object
            properties:
              msg:
                type: string
       
 
  /comment/delete/{comment_id}/:
    delete:
      tags:
        - comment
      summary: 删除评论
      parameters:
        - name: token
          in: header
          required: true
          type: string
        - name: comment_id
          in: query
          required: true
          type: string      
      responses:
        200:
          description: success
          schema:
            type: object
            properties:
              msg:
                type: string

        400:
          description: 请求错误
          schema:
            type: object
            properties:
              msg:
                type: string
        401:
          description: 身份认证错误
          schema:
            type: object
            properties:
              msg:
                type: string
        404:
          description: 未找到
          schema:
            type: object
            properties:
              msg:
                type: string
 
    
  /secret/square/:
    get:
      tags:
        - secret
      summary: 黑夜广场(请求秘密)　
      description: secrets
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: token
          in: header
          required: true
          type: string 
        - name: page
          in: query
          type: integer
      responses:
        200:
          description: successful operation
          schema:
            type: object
            properties:
              msg:
                type: string
              secrets:
                type: array
                items:
                  properties:
                    secret_id:
                      type: string   #   不显示
                    colour:
                      type: integer
                    content:
                      type: string
                    send_time:
                      type: string
        400:
          description: 请求错误
          schema:
            type: object
            properties:
              msg:
                type: string
        401:
          description: 身份认证错误
          schema:
            type: object
            properties:
              msg:
                type: string
                
 
